version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  pg_data:
    name: pg_data

networks:
  backend-network:
    name: backend-network